---

- name: Clear current BuildBot user ssh key
  file:
    name: "{{ buildbot_home}}/{{ item }}"
    state: absent
  become: yes
  with_items:
    - .ssh/id_rsa
    - .ssh/id_rsa.pub
    - .ssh/authorized_keys

- name: Clear any local copy of ssh key
  file:
    name: .ssh
    state: absent
  connection: local

- name: Generate new BuildBot SSH key
  user:
    name: "{{ buildbot_user }}"
    home: "{{ buildbot_home }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
  become: yes

- name: Fetch BuildBot SSH keys
  fetch:
    src: "{{buildbot_home}}/{{ item }}"
    dest: "{{ item }}"
    flat: yes
  become: yes
  with_items:
    - .ssh/id_rsa
    - .ssh/id_rsa.pub

- name: Adding local keys
  local_action: shell cp group_vars/keys/* .ssh/ | true

- name: Populate BuildBot master authorized_keys
  authorized_key:
    user: "{{ buildbot_user }}"
    state: present
    key: "{{ lookup('file', '.ssh/id_rsa.pub') }}"
    manage_dir: yes
  become: yes
