---

- name: Create Buildbot group
  group:
    name: '{{ buildbot_user }}'
    state: present
  become: yes

- name: Create Buildbot user
  user:
    name: '{{ buildbot_user }}'
    password: "{{ lookup('password', '/dev/null encrypt=sha1_crypt length=32') }}"
    update_password: always
    home: "{{ buildbot_home }}"
    shell: /sbin/nologin
    groups: buildbot,docker
  become: yes
  when: create_buildbot_user and 'master' not in group_names

- name: Create Buildbot SSH key directory
  file:
    path: "{{ buildbot_home }}/.ssh"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: 0700
    state: directory
  become: yes

- name: Push Buildbot SSH keys
  copy:
    src: ".ssh/{{ groups['master'][0] }}/"
    dest: "{{ buildbot_home }}/{{ item.dest }}/"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: 0600
    force: yes
  with_items:
    - { dest: ".ssh", owner: "{{ buildbot_user }}" }
     #Note: This is the hardcoded buildbot user inside the docker image, do not change this
    - { dest: "ssh", owner: "1000" }
  become: yes
  notify: "Start Autossh"

