---

- name: Create Buildbot group
  group:
    name: '{{ buildbot_user }}'
    state: present
  become: yes

- name: Create Buildbot user
  user:
    name: '{{ buildbot_user }}'
    password: "{{ lookup('password', '/dev/null encrypt=sha1_crypt length=32') }}"
    update_password: always
    home: "{{ buildbot_home }}"
    shell: /sbin/nologin
    groups: buildbot,docker
  become: yes
  when: create_buildbot_user and 'master' not in group_names

- name: Create Buildbot SSH key directory
  file:
    path: "{{ buildbot_home }}/{{ item }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: 0700
    state: directory
  with_items:
    - "ssh"
  become: yes

- name: Push Buildbot SSH keys
  template:
    src: "{{ item.src }}"
    dest: "{{ buildbot_home }}/ssh/"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: 0600
    force: yes
  with_filetree:
    - ".ssh/{{ groups['master'][0] }}/"
  become: yes
  notify: "Start Autossh"

