---

- name: Start BuildBot
  service:
    name: buildbot
    state: restarted
    enabled: yes
  become: yes

- name: Start BuildBot worker
  service:
    name: buildbot-worker
    state: restarted
    enabled: yes
  become: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
