---

- hosts: all
  become: yes
  tasks:
    - name: Activate EPEL
      package:
        name: epel-release
        state: latest
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 8"

- hosts: all
  become: yes
  roles:
    - nginx
    - opencast-allinone
