---

- hosts: all
  become: yes
  tasks:
    - name: Activate EPEL
      package:
        name: epel-release
        state: latest
      when: >
        ansible_distribution == 'CentOS'
        or ansible_distribution == 'RedHat'
        or ansible_distribution == 'Scientific'

- hosts: all
  become: yes
  roles:
    - nginx
    - opencast-allinone
