---

- name: Install BuildBot system level dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - ca-cacert
    - ca-certificates
    - python-pip
    - python-dev
    - python-virtualenv
    - build-essential
    - git
    - sudo

- name: Install nginx
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  when: config_nginx
  with_items:
    - nginx
