---

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Update Python pip
  pip:
    name: "{{ item }}"
    virtualenv: "{{ buildbot_base }}"
    state: latest
  become: yes
  with_items:
    - pip

- name: Install BuildBot Python level dependencies
  pip:
    name: "{{ item }}"
    virtualenv: "{{ buildbot_base }}"
    state: latest
  become: yes
  with_items:
    - buildbot[bundle]
    - treq
    - requests
    - pyopenssl
    - enum
    - certifi
    - urllib3[secure]

- name: Create BuildBot user
  user:
    name: '{{ buildbot_user }}'
    password: '$6$rounds=656000$wuuAoKugbM31ca7G$4ixDGH6.G54ZLIfepc4LhiNsV5UUxeXdfh/3fFhjrsvW3Jg9CgjsMta66hcM/41AptJoTq0wX1ebN03k.2hso/'
    update_password: always
    home: "{{ buildbot_home }}"
    shell: /sbin/nologin
  become: yes
  when: create_buildbot_user

- name: Ensure BuildBot master parent directory exists and has the right permissions
  file:
    state: directory
    path: "{{ buildbot_home }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    recurse: yes
  become: yes

- name: Ensure BuildBot master artifact directory exists and has the right permissions
  file:
    state: directory
    path: "{{ disk_base }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
  become: yes

- name: Create BuildBot master instance
  shell: "{{ buildbot_create_master }}"
  args:
    chdir: "{{ buildbot_home }}"
  become: yes
  become_user: "{{ buildbot_user }}"

- name: Copy default BuildBot master configuration
  shell: "cp {{ buildbot_master_config }}.sample {{ buildbot_master_config }}"
  become: yes
  become_user: "{{ buildbot_user }}"

- name: Apply BuildBot master configuration
  shell: "{{ buildbot_apply }}"
  args:
    chdir: "{{ buildbot_home }}"
  become: yes
  become_user: "{{ buildbot_user }}"

- name: Clear current BuildBot user ssh key
  file:
    name: "{{ item }}"
    state: absent
  become: yes
  become_user: "{{ buildbot_user }}"
  with_items:
    - .ssh/id_rsa
    - .ssh/id_rsa.pub

- name: Generate new BuildBot SSH key
  user:
    name: "{{ buildbot_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
  become: yes

- name: Fetch BuildBot SSH keys
  fetch:
    src: {{ item }}
    dest: {{ item }}
    flat: yes
  become: yes
  become_user: "{{ buildbot_user }}"
  with_items:
    - .ssh/id_rsa
    - .ssh/id_rsa.pub

- name: Populate BuildBot master authorized_keys
  authorized_key:
    user: "{{ buildbot_user }}"
    state: present
    key: .ssh/id_rsa.pub
    manage_dir: yes
  become: yes

- name: Template Buildbot nginx config
  template:
    src: buildbot.conf
    dest: /etc/nginx/conf.d/buildbot.conf
    force: yes
    owner: root
    group: root
  when: config_nginx
  notify: "Restart nginx"

- name: Template Buildbot master systemd unit file
  template:
    src: buildbot.service
    dest: /etc/systemd/system/buildbot.service
    force: yes
    owner: root
    group: root
  notify: "Start BuildBot"

- name: Template Buildbot cleanup script
  template:
    src: cleaner.sh
    dest: "{{ buildbot_base }}/cleaner.sh"
    force: yes
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
  become: yes

- name: Add Buildbot cleanup script to the crontab
  cron:
    name: "Remove old build artifacts"
    special_time: daily
    job: "/bin/bash {{ buildbot_base }}/cleaner.sh"
    user: "{{ buildbot_user }}"
    state: present
  become: yes
