version: '2'
services:
  buildbot:
    image: greglogan/ocqa-buildbot-master:latest
    env_file:
      - db.env
    environment:
      - BUILDBOT_CONFIG_DIR=config
      - BUILDBOT_WORKER_PORT=9989
    depends_on:
      - db
    ports:
      - "{{ buildbot_port }}:{{ buildbot_port }}"
      #Note: We're only exposing the worker port to localhost on the master node since comms are done via SSH tunnel
      - "127.0.0.1:9989:9989"
    network_mode: "host"
    volumes:
      - "{{ buildbot_home }}/buildbot-config:/var/lib/buildbot"
      - "{{ buildbot_home }}/sockets:{{ buildbot_home }}/sockets"
  proxy:
    image: "nginx:stable"
    ports:
      - "80:80"
    network_mode: "host"
    volumes:
      - "{{ buildbot_home }}/nginx-config:/etc/nginx/conf.d"
      - "{{ disk_base }}:{{ disk_base }}"
  db:
    env_file:
      - db.env
    image: "postgres:9.4"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "{{ buildbot_home }}/postgres-data:/var/lib/postgresql/data"
