---
# vim: et:ts=2:sw=2:sts=2
# This playbook deploys a Buildbot master and worker(s) configured for Opencast

- hosts: all
  user: "{{ login_user }}"
  roles:
    #We're becoming here because the docker role does not become inside of itself
    - { role: geerlingguy.docker, become: yes }
    - docker-tcp-connectable
    - buildbot-base
    - buildbot-keysync
    - autossh
  handlers:
    - import_tasks: handlers/handlers.yml

- hosts: master
  user: "{{ login_user }}"
  roles:
    - buildbot-master-install
    - { role: buildbot-master-config, tags: reconfig }
  handlers:
    - import_tasks: handlers/handlers.yml


- hosts: workers
  user: "{{ login_user }}"
  roles:
    - { role: buildbot-worker, when: "'master' not in group_names" }
  handlers:
    - import_tasks: handlers/handlers.yml
