---

- name: Ensure Buildbot directories exists and has the right permissions
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
  become: yes
  with_items:
    - { path: "{{ buildbot_config_master }}", mode: "0700" }
    - { path: "{{ buildbot_config_master }}/envs", mode: "0700" }

- name: Template Buildbot public support files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
    force: yes
  become: yes
  with_items:
    - { src: "mini-dinstall.conf", dest: "{{ buildbot_config_master }}/mini-dinstall.conf", mode: "644" }
    - { src: "deb_sign.sh", dest: "{{ buildbot_config_master }}/deb_sign.sh", mode: "755" }
    - { src: "envs/stable", dest: "{{ buildbot_config_master }}/envs/stable", mode: "0644" }
    - { src: "envs/develop", dest: "{{ buildbot_config_master }}/envs/develop", mode: "0644" }
    - { src: "envs/legacy", dest: "{{ buildbot_config_master }}/envs/legacy", mode: "0644" }

- name: Adding ssh host config data to workers
  blockinfile:
    path: "{{ buildbot_home }}/.ssh/config"
    create: yes
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "0644"
    block: "{{ lookup('template', 'roles/buildbot-config/templates/ssh_config') }}"
  become: yes
