---

- name: Ensure Buildbot directories exists and has the right permissions
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
  become: yes
  with_items:
    - { path: "{{ buildbot_config_master }}", mode: "0700" }

- name: Template Buildbot public support files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
    force: yes
  become: yes
  with_items:
    - { src: "mini-dinstall.conf", dest: "{{ buildbot_config_master }}/mini-dinstall.conf", mode: "644" }
    - { src: "deb_sign.sh", dest: "{{ buildbot_config_master }}/deb_sign.sh", mode: "755" }

