---
# vim: et:ts=2:sw=2:sts=2

- hosts: server

  vars:
    admins:
      - lars
      - greglogan
    bots:
      - buildbot

  tasks:
    - name: install epel (rh)
      become: yes
      package:
        state=present
        name={{ item }}
      loop:
        - epel-release
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 8"

    - name: install base tools
      become: yes
      package:
        state: present
        name: '{{ item }}'
      loop:
        - git
        - htop
        - nload
        - vim
        - zsh

    - name: Ensure group wheel exists
      group:
        name: wheel
        state: present

    - name: create opencast admin infra users
      become: yes
      user:
        name: '{{ item }}'
        groups: wheel
        append: yes
      loop: '{{ admins }}'

    - name: create opencast bot infra users
      become: yes
      user:
        name: "{{ item }}"
      loop: "{{ bots }}"

    - name: add vmusers groups uos servers
      become: yes
      user:
        name: '{{ item }}'
        groups: vmusers
        append: yes
      loop: '{{ admins + bots }}'
      when: "'uos' in group_names"

    - name: set up admin authorized keys
      become: yes
      authorized_key:
        user: '{{ item }}'
        state: present
        key: "{{ lookup('file', 'pub-keys/{{ item }}.pub') }}"
        exclusive: True
      loop: '{{ admins }}'

    - name: set up bot authorized keys
      become: yes
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', 'pub-keys/' ~ item ~ '-' ~ inventory_hostname.split('.') | first ~ '.pub' ) }}"
        exclusive: True
      tags: test
      loop: "{{ bots }}"

    - name: remove old users
      become: yes
      user:
        name: '{{ item }}'
        state: absent
        remove: yes
      loop: "{{ remove_user | default([]) }}"
      when: item != ""

    - name: allow wheel to sudo without a password
      become: yes
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"


    # sshd options

    - name: disable password authentication
      become: yes
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        line: 'PasswordAuthentication no'
      notify:
        - reload sshd


  handlers:
    - name: reload sshd
      become: yes
      service:
        name: sshd
        state: reloaded
