---
# vim: et:ts=2:sw=2:sts=2

- hosts: server

  vars:
    admins:
      - lars
      - greglogan

  tasks:
    - name: install epel (rh)
      become: yes
      package:
        state=present
        name={{ item }}
      with_items:
        - epel-release
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: install base tools
      become: yes
      package:
        state: present
        name: '{{ item }}'
      with_items:
        - git
        - htop
        - nload
        - vim

    - name: create opencast infra users
      become: yes
      user:
        name: '{{ item }}'
        password: '$6$rounds=656000$/2a4a2lmJtsLBdyM$0VVKwJ4byUPaLirCwdvfgTXRg7dLptq4UVVt/ge9sahNSzHYUYcv9aq/O7ytiuShicXVPya5SjLX8CSyGfKWs/'
        update_password: on_create
      with_items:
        - "{{ admins }}"
        - "{{ host_admins | default([]) }}"
      when: item != ""

    - name: add vmusers and vmadmins groups uos servers
      become: yes
      user:
        name: '{{ item }}'
        groups: vmusers,vmadmins
        append: yes
      with_items:
        - "{{ admins }}"
        - "{{ host_admins | default([]) }}"
      when:
        - item != ""
        - "'uos' in group_names"

    - name: add wheel group
      become: yes
      user:
        name: '{{ item }}'
        groups: wheel
        append: yes
      with_items:
        - "{{ admins }}"
        - "{{ host_admins | default([]) }}"
      when: item != ""

    - name: set up authorized keys
      become: yes
      authorized_key:
        user: '{{ item }}'
        state: present
        key: "{{ lookup('file', 'pub-keys/{{ item }}.pub') }}"
      with_items:
        - "{{ admins }}"
        - "{{ host_admins | default([]) }}"
      when: item != ""

    - name: remove old users
      become: yes
      user:
        name: '{{ item }}'
        state: absent
        remove: yes
      with_items:
        - "{{ remove_user | default([]) }}"
      when: item != ""


    # sshd options

    - name: disable password authentication
      become: yes
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        line: 'PasswordAuthentication no'
      notify:
        - reload sshd


  handlers:
    - name: reload sshd
      become: yes
      service:
        name: sshd
        state: reloaded
