---

#Where Builbot lives, relative to the webserver root.  Leave this alone to have http://$servername/ be buildbot
#String needs to start with a non-slash, and end with a slash (ie, buildbot/, not /buildbot or /builtbot/)
buildbot_url: ""

#Build url base
build_url_base: /builds

#Build url with build properties
build_artifacts_url: "{{ build_url_base }}/%(prop:branch_pretty)s/%(prop:buildnumber)s-%(prop:build_timestamp)s"

#Build location on master filesystem
build_dest_base: /var/www/buildbot

#Build location on master filesystem
build_dest: "{{ build_dest_base }}/%(prop:branch_pretty)s/%(prop:buildnumber)s-%(prop:build_timestamp)s"

#Build locatino for child builds.  This is used by the reports and debs.
build_master_src: "{{ build_dest_base }}/%(prop:branch_pretty)s/%(prop:parent_build)s-%(prop:build_timestamp)s"

#The location on disk to deploy the reports to
deployed_reports: "{{ build_dest }}/reports/%(prop:branch_pretty)s"

#The oath bits
bitbucket_oath_client_id:
bitbucket_oath_client_secret:
