---

- name: install lkiesow/minio copr repository
  yum_repository:
    file: lkiesow-minio-epel-7.repo
    name: lkiesow-minio
    description: 'Copr repo for minio owned by lkiesow'
    baseurl: "https://copr-be.cloud.fedoraproject.org/results\
              /lkiesow/minio/epel-7-$basearch/"
    enabled: true
    gpgcheck: true
    gpgkey: "https://copr-be.cloud.fedoraproject.org/results\
             /lkiesow/minio/pubkey.gpg"

- name: create minio user
  user:
    name: minio
    state: present

- name: create opencast data directory
  file:
    path: /srv/minio
    state: directory
    mode: 0775
    owner: minio
    group: minio

- name: install minio and ntpd
  package:
    name: '{{ item }}'
    state: present
  loop:
    - minio
    - ntp

- name: configure minio path
  lineinfile:
    path: /etc/minio/minio.conf
    regexp: '^MINIO_VOLUMES='
    line: MINIO_VOLUMES=/srv/minio/
  notify: restart minio

- name: enable ntpd
  service:
    name: ntpd
    state: started
    enabled: true

- name: enable minio service
  service:
    name: minio
    state: started
    enabled: true
