version: '2'
services:
  maria:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  mysql:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
