---

- name: Install EPEL release
  yum:
    name: epel-release
    state: latest
    update_cache: yes
  become: yes

- name: Install Buildbot system level dependencies
  yum:
    name: [ 'autossh', 'sudo', 'python-pip' ]
    state: latest
  become: yes
