---

- name: Install EPEL release
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - epel-release

- name: Install BuildBot system level dependencies
  yum:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - autossh
    - sudo
    - python-pip
