---

- name: Install BuildBot system level dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv
    - build-essential
    - git
    - openjdk-8-jdk
    - maven
    - dpkg-dev
    - devscripts
    - dh-exec
    - sudo
#TODO: Needs ffmpeg!

- name: Install BuildBot Python level dependencies
  pip:
    name: "{{ item }}"
    virtualenv: "{{ buildbot_base }}"
  become: yes
  with_items:
    - buildbot-worker

- name: Create BuildBot user
  user:
    name: '{{ buildbot_user }}'
    password: '$6$rounds=656000$wuuAoKugbM31ca7G$4ixDGH6.G54ZLIfepc4LhiNsV5UUxeXdfh/3fFhjrsvW3Jg9CgjsMta66hcM/41AptJoTq0wX1ebN03k.2hso/'
    update_password: always
    home: "{{ buildbot_home }}"
    shell: /sbin/nologin
  become: yes
  when: create_buildbot_user

- name: Ensure BuildBot master parent directory exists and has the right permissions
  file:
    state: directory
    path: "{{ buildbot_base }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
  become: yes

- name: Create BuildBot worker instance
  shell: "{{ buildbot_create_worker }}"
  args:
    chdir: "{{ buildbot_home }}"
  become: yes
  become_user: "{{ buildbot_user }}"

- name: Template BuildBot worker configuration
  template:
    src: "{{ item }}"
    dest: "{{ buildbot_base }}/info/{{ item }}"
    owner: "{{ buildbot_user }}"
    force: yes
  become: yes
  become_user: "{{ buildbot_user }}"
  with_items:
    - admin
    - host

- name: Template Buildbot master defaults
  template:
    src: buildbot-worker.default
    dest: /etc/default/buildbot-worker.default
    force: yes
    owner: root
    group: root

- name: Template Buildbot master init script
  template:
    src: buildbot-worker.init.sh
    dest: /etc/init.d/buildbot-worker
    force: yes
    owner: root
    group: root
  notify: "Start BuildBot worker"

- name: Template Buildbot master systemd unit file
  template:
    src: buildbot-worker.service
    dest: /etc/systemd/system/buildbot-worker.service
    force: yes
    owner: root
    group: root
  notify: "Start BuildBot worker"
