---

- name: Installing apt-transport-https
  apt:
    pkg: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
  become: yes

- name: Adding Debian signing key to apt keyring
  apt_key:
    url: "{{ oc_deb_repo_key }}"
    id: "{{ oc_deb_repo_key_id }}"
    state: present
  become: yes

- name: Adding pkg.opencast.org to repo list
  apt_repository:
    repo: "{{oc_deb_repo_url}}"
    state: present
    update_cache: yes
  become: yes

- name: Install BuildBot system level dependencies
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv
    - build-essential
    - git
    - openjdk-8-jdk
    - maven
    - dpkg-dev
    - devscripts
    - dh-exec
    - sudo
    - ffmpeg
    - autossh
