---

- name: Install BuildBot system level dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: yes
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv
    - build-essential
    - git
    - openjdk-8-jdk
    - maven
    - dpkg-dev
    - devscripts
    - dh-exec
    - sudo
#TODO: Needs ffmpeg!
