---

- import_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Ensuring Docker is connectable via TCP
  replace:
    path: /lib/systemd/system/docker.service
    regexp: "dockerd -H fd://$"
    replace: "dockerd -H fd:// -H tcp://localhost:2375"
  become: yes
  notify: "Restart Docker"

- name: Create BuildBot user
  user:
    name: '{{ buildbot_user }}'
    password: "{{ lookup('password', '/dev/null encrypt=sha1_crypt length=32') }}"
    update_password: always
    home: "{{ buildbot_home }}"
    shell: /sbin/nologin
    groups: buildbot,docker
  become: yes
  when: create_buildbot_user

- name: Ensure BuildBot parent directory exists and has the right permissions
  file:
    state: directory
    path: "{{ buildbot_home }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    recurse: yes
  become: yes

- name: Templating guest config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: 0755
  with_items:
    - { src: debsetup.sh, dest: "{{ buildbot_home }}/debsetup.sh" }
    - { src: centsetup.sh, dest: "{{ buildbot_home }}/centsetup.sh" }
  become: yes

