---

- name: install nginx
  package:
    name: nginx
    state: present

- name: create ssl directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: configure nginx additional files
  copy:
    src: "{{item.key}}"
    dest: /etc/nginx/{{item.value}}
    owner: root
    group: root
    mode: 0640
  with_items:
    - { key: mime.types,      value: mime.types }
    - { key: certificate.pem, value: "ssl/{{inventory_hostname}}.crt" }
    - { key: key.pem,         value: "ssl/{{inventory_hostname}}.key" }

- name: create diffie hellman ephemeral parameters for nginx
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  args:
    creates: /etc/nginx/ssl/dhparam.pem

- name: dhparam.pem file permission
  file:
    path: /etc/nginx/ssl/dhparam.pem
    owner: root
    group: root
    mode: 0640

- name: configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0640
  notify: reload nginx

- name: start and enable nginx
  service:
    name={{item}}
    enabled=true
    state=started
  with_items:
    - nginx
