---

- name: Detect BuildBot home directory
  shell: >
          egrep "^buildbot:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: buildbot_home

- name: Template BuildBot master configuration
  template:
    src: master.cfg
    dest: "{{ buildbot_home.stdout_lines[0] }}/{{ inventory_hostname }}/master.cfg"
    owner: buildbot
    force: yes
  become: yes
  become_user: buildbot

- name: Apply BuildBot master configuration
  shell: buildbot reconfig {{ inventory_hostname }}
  args:
    chdir: "{{ buildbot_home.stdout_lines[0] }}"
  become: yes
  become_user: buildbot
  notify: "Ensure BuildBot master started"
