---

- name: Template BuildBot master configuration
  template:
    src: master.cfg
    dest: "{{ buildbot_master_config }}"
    owner: "{{ buildbot_user }}"
    force: yes
  become: yes
  become_user: "{{ buildbot_user }}"

- name: Apply BuildBot master configuration
  shell: "{{ buildbot_apply }}"
  args:
    chdir: "{{ buildbot_home }}"
  become: yes
  become_user: "{{ buildbot_user }}"
  #Note: We're using the notify here because the above is not triggering the re-read of the config file
  notify: "Reload BuildBot"
